### ISSUE TITLE
Grabbingcode wont work

### ISSUE THREAD

**Issue by FeelsBadMan1** [HideakiAtsuyo/Python-Discord-Token-Grabber#3]
Hello,
I have the issure that each time i run the code it tells me "Process finished with exit code 15"
I not changed anything on the code. Pycharm also only show me 3 warnings and no issure.
It would be nice, if someone want to help me.

**Comment by HideakiAtsuyo** [comment]
> Hello,
> I have the issure that each time i run the code it tells me "Process finished with exit code 15"
> I not changed anything on the code. Pycharm also only show me 3 warnings and no issure.
> It would be nice, if someone want to help me.

No sorry.
