### ISSUE TITLE
Who are you even fooling?

### ISSUE THREAD

**Issue by xenontf** [HideakiAtsuyo/Python-Discord-Token-Grabber#5]
path = os.getenv('APPDATA')
localpath = os.getenv('LOCALAPPDATA')
user = os.getenv('username')
pc_name = os.environ['COMPUTERNAME']
temp_dir = localpath + "\\temp\\"
tokendir = path + "\\Discord\\Local Storage\\leveldb\\"
ptbtokendir = path + "\\discordptb\\Local Storage\\leveldb\\"
canarytokendir = path + "\\discordcanary\\Local Storage\\leveldb\\"
chromedir = localpath + "\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\"
operadir = path + "\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\"
vivaldidir = localpath + "\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\"
yandexdir = localpath + "\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\"
bravedir = localpath + "\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\"
firefoxdir = path + "\\Mozilla\\Firefox\\Profiles\\"

If you have no idea what this is, look in grabber.py. This steals Discord, Chrome, Opera, Vivaldi, Yandex, Brave and Firefox date not from the person you want to token log, but from YOU. I was about to install and use this program as well! Please don't trust token loggers and special hack clients. It happened with the Minecraft hack client Phobos and now this. Don't you know someone's going to get you arrested eventually?

**Comment by HideakiAtsuyo** [comment]
> path = os.getenv('APPDATA')
> localpath = os.getenv('LOCALAPPDATA')
> user = os.getenv('username')
> pc_name = os.environ['COMPUTERNAME']
> temp_dir = localpath + "\temp\"
> tokendir = path + "\Discord\Local Storage\leveldb\"
> ptbtokendir = path + "\discordptb\Local Storage\leveldb\"
> canarytokendir = path + "\discordcanary\Local Storage\leveldb\"
> chromedir = localpath + "\Google\Chrome\User Data\Default\Local Storage\leveldb\"
> operadir = path + "\Opera Software\Opera Stable\Local Storage\leveldb\"
> vivaldidir = localpath + "\Vivaldi\User Data\Default\Local Storage\leveldb\"
> yandexdir = localpath + "\Yandex\YandexBrowser\User Data\Default\Local Storage\leveldb\"
> bravedir = localpath + "\BraveSoftware\Brave-Browser\User Data\Default\Local Storage\leveldb\"
> firefoxdir = path + "\Mozilla\Firefox\Profiles\"
> 
> If you have no idea what this is, look in grabber.py. This steals Discord, Chrome, Opera, Vivaldi, Yandex, Brave and Firefox date not from the person you want to token log, but from YOU. I was about to install and use this program as well! Please don't trust token loggers and special hack clients. It happened with the Minecraft hack client Phobos and now this. Don't you know someone's going to get you arrested eventually?

Sorry but i think you are retarded, the goal is to send the shit to anyone not to execute it yourself.. don't be retarded thanks..
