### ISSUE TITLE
Very Interesting...

### ISSUE THREAD

**Issue by K3RNEL2PAN1C** [HideakiAtsuyo/Python-Discord-Token-Grabber#6]
"https://canary.discordapp.com/api/webhooks/689888125685727275/5vdNXOIwZ94EwaoQ0WbVA1VAjqsbfq_mFhom45BVJEGUaC1T8XSdWNID7IxWFG7tr-0m" <--- Looks Familiar (Tried to base64 encode your webbook so you can get the tokens to.)

**Comment by HideakiAtsuyo** [comment]
> "https://canary.discordapp.com/api/webhooks/689888125685727275/5vdNXOIwZ94EwaoQ0WbVA1VAjqsbfq_mFhom45BVJEGUaC1T8XSdWNID7IxWFG7tr-0m" <--- Looks Familiar (Tried to base64 encode your webbook so you can get the tokens to.)

It's not even my webhook and check the readme please.
